[package]
name = "bank-statement-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
nom = "7.1.3"
pdf-extract = "0.6.4"
tempfile = "3.5.0"
